### PR TITLE
Bumping minor version of civis to 1.2.0

### PR DESCRIPTION
**Pull request by keithing**

### CODE REVIEW

**Review by stephen-hoover — CHANGES_REQUESTED** [review]
Please also add a note to the changelog. I think this qualifies as a new minor version for the container; I'll make that change in a different PR.

**Comment by keithing** [comment]
I assume the changes under `[1.0.1] - 2017-02-13` should be lumped into `[1.1.0] - 2017-02-09` ?

**Comment by stephen-hoover** [comment]
Make it tomorrow's date, but yes.

**Review by stephen-hoover — APPROVED** [review]
LGTM!

**Pull request merged**
