### PR TITLE
ENH move conda to root env

### PR DESCRIPTION
**Pull request by beckermr**
Let's try this.

### CODE REVIEW

**Review by stephen-hoover — CHANGES_REQUESTED** [review]
Could you add a note to the changelog and modify the documentation in the README? Also, please describe the motivation for these changes in more detail both in the original post and in the commit message.

Is there a test that will verify that this does what you want it to? The existing tests do a good job of checking that we're still in the right environment, so that's okay.

**Comment by beckermr** [comment]
Good point! Will do!

**Comment by stephen-hoover** [comment]
You should also bump the release date to the 13th while you're adding to the changelog.

**Comment by beckermr** [comment]
It could be argued that moving the install from `datascience` to `root` for conda satisfies the criterion for a major version change.

    A major version will increase if there are any backwards-incompatible changes in any 
    of the packages contained in this Docker image, or any other backwards-incompabile 
    changes in the execution environment.

**Comment by stephen-hoover** [comment]
@beckermr , could you pull out the bugfix portions of this PR (pinning conda and the version tweaks to get rid of MKL) into a separate PR? Let's put that into v1.1 and make this environment fix v2.

**Comment by beckermr** [comment]
Yep sure.

**Comment by beckermr** [comment]
Let's wait for tests, but this should be good to go.

**Review by stephen-hoover — CHANGES_REQUESTED** [review]
Two change requests: 
- Could you leave the date blank for v2 on the changelog?
- Please update the environment variable version numbers at the bottom of the file to reflect v2.0.0.

**Comment by beckermr** [comment]
Will do! Good catch!

**Comment by beckermr** [comment]
Done!

**Review by stephen-hoover — APPROVED** [review]
LGTM

**Pull request merged**
