### PR TITLE
DEP Update versions of boto3, botocore, and awscli

### LINKED ISSUE #57: Incompatible dependencies: boto3 and botocore
When pip installing packages on top of the datascience-python docker image v4.0.1, the following warning shows up in the logging:

```
boto3 1.5.11 has requirement botocore<1.9.0,>=1.8.25, but you'll have botocore 1.5.38 which is incompatible.
```

As a sanity check, `environment.yml` indeed has `boto3` pinned down at 1.5.11 and `botocore` at 1.5.38:

https://github.com/civisanalytics/datascience-python/blob/v4.0.1/environment.yml#L7-L9

Also, `boto3` 1.5.11 does specify `botocore>=1.8.25,<1.9.0`:

https://github.com/boto/boto3/blob/1.5.11/setup.py#L17

Instead of submitting a pull request right away, I thought I should create an issue first, just in case the incompatible dependencies between `boto3` and `botocore` were intentional for reasons I'm unaware of, and also because there are likely other dependencies that we should probably update as well (it's been two months since the v4.0.1 release in early February 2018) but I don't know if the maintainers (@stephen-hoover?) are already working on it.

### PR DESCRIPTION
**Pull request by jacksonllee**
As per offline discussion with @stephen-hoover, this PR resolves #57 to update the versions of `boto3` and `botocore` for a release. (Other packages in `environment.yml` probably also need updating for their versions, but this will be done separately in the near future.)

@stephen-hoover, I haven't updated `CHANGELOG.md` and `Dockerfile` for a new version number. Please let me know if you want me to pin down a new one within this PR as well (if you do, it is 4.1.0 for a minor release as this PR updates the minor versions of included packages, correct?).

Update: This PR also updates the version of `awscli` to 1.15.4, as it requires `botocore`.

### CODE REVIEW

**Comment by stephen-hoover** [comment]
I think this also needs an awscli update. That tracks botocore directly, IIRC. It looks like there's an up-to-date version of it on conda-forge now. Try moving awscli to the conda section and pinning to 1.15.4.

**Review by stephen-hoover — CHANGES_REQUESTED** [review]
I think this also needs an awscli update. That tracks botocore directly, IIRC. It looks like there's an up-to-date version of it on conda-forge now. Try moving awscli to the conda section and pinning to 1.15.4.

**Comment by jacksonllee** [comment]
`awscli` is now updated as well, and so are the PR title and description.

**Review by stephen-hoover — APPROVED** [review]
Thank you! LGTM.

If you open a new PR to increase the version number, we can tag a new version tomorrow. You're right that this should be a minor version increase.

**Comment by jacksonllee** [comment]
@stephen-hoover Will do -- a new PR coming your way now.

**Pull request merged**
