### PR TITLE
MAINT Update version number to 3.0.0

### PR DESCRIPTION
**Pull request by stephen-hoover**
Prepare for next release

### CODE REVIEW

**Comment by beckermr** [comment]
There is an ipython major version change. Not sure if we need to start at 3.0.0 now....

**Comment by stephen-hoover** [comment]
Arguably every pandas minor version increase is a breaking change. IPython's changes look rather light -- I think that removing Python 2 support was their big breaking change. http://ipython.readthedocs.io/en/stable/whatsnew/version6.html#backward-incompatible-changes

I bumped to v3.0.0 anyway.

**Comment by beckermr** [comment]
Agreed on the pandas changes. Sounds good.

**Comment by stephen-hoover** [comment]
@beckermr , I updated the date to today. I think we're ready to merge this and release. What do you think?

**Comment by beckermr** [comment]
Shall we take guesses on when we get to version 10, price-is-right style? :) J/K. (But I have October 1st 2017!)

LGTM!

**Review by beckermr — APPROVED** [review]

**Pull request merged**
