### PR TITLE
DEP Release v6.0.0

### PR DESCRIPTION
**Pull request by elsander**
This PR updates dependencies for version 6 of datascience-python.

Tagging @jacksonllee to confirm that no changes interfere with CivisML dependencies (I think `pyarrow` is the only one that overrides your previous updates?)

### CODE REVIEW

**Comment by elsander** [comment]
@channiemills I'm not sure why the circle tests are showing as pending. When you click through, it shows that the tests succeeded. This should be ready for review.

**Comment by channiemills** [comment]
Just want to confirm, does the Dockerfile need updating for the new civis conda and civis python versions? I saw they were updated in the [last DEP release PR](https://github.com/civisanalytics/datascience-python/pull/66/files#diff-3254677a7917c6c01f55212f86c57fbfR15-R16).

**Comment by channiemills** [comment]
Ah, nevermind I see they must have been updated in a previous PR, just not in this diff.

**Review by channiemills — APPROVED** [review]
LGTM

**Review by jacksonllee — APPROVED** [review]
LGTM with respect to CivisML -- I confirm that all package versions here are compatible with the next CivisML release.

**Pull request merged**
